# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Additem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 369)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAcceptDrops(True)
        self.frame.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 51, 31))
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 120, 101, 31))
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 91, 31))
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(10, 250, 81, 31))
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.pushButtonsubmit = QtWidgets.QPushButton(self.frame)
        self.pushButtonsubmit.setGeometry(QtCore.QRect(30, 300, 151, 31))
        self.pushButtonsubmit.setStyleSheet("background-color: rgb(0, 139, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButtonsubmit.setObjectName("pushButtonsubmit")
        self.lineEdititem = QtWidgets.QLineEdit(self.frame)
        self.lineEdititem.setGeometry(QtCore.QRect(60, 60, 311, 31))
        self.lineEdititem.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdititem.setMaxLength(40)
        self.lineEdititem.setClearButtonEnabled(False)
        self.lineEdititem.setObjectName("lineEdititem")
        self.lineEditdescription = QtWidgets.QLineEdit(self.frame)
        self.lineEditdescription.setGeometry(QtCore.QRect(110, 120, 261, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditdescription.sizePolicy().hasHeightForWidth())
        self.lineEditdescription.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditdescription.setFont(font)
        self.lineEditdescription.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.lineEditdescription.setAutoFillBackground(False)
        self.lineEditdescription.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lineEditdescription.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.lineEditdescription.setMaxLength(1000)
        self.lineEditdescription.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditdescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEditdescription.setDragEnabled(True)
        self.lineEditdescription.setReadOnly(False)
        self.lineEditdescription.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEditdescription.setClearButtonEnabled(False)
        self.lineEditdescription.setObjectName("lineEditdescription")
        self.lineEditunitprice = QtWidgets.QLineEdit(self.frame)
        self.lineEditunitprice.setGeometry(QtCore.QRect(100, 200, 271, 31))
        self.lineEditunitprice.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lineEditunitprice.setMaxLength(40)
        self.lineEditunitprice.setClearButtonEnabled(False)
        self.lineEditunitprice.setObjectName("lineEditunitprice")
        self.lineEditquantity = QtWidgets.QLineEdit(self.frame)
        self.lineEditquantity.setGeometry(QtCore.QRect(90, 250, 281, 31))
        self.lineEditquantity.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lineEditquantity.setMaxLength(40)
        self.lineEditquantity.setClearButtonEnabled(False)
        self.lineEditquantity.setObjectName("lineEditquantity")
        self.pushButtonsubmit_2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonsubmit_2.setGeometry(QtCore.QRect(220, 300, 151, 31))
        self.pushButtonsubmit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButtonsubmit_2.setObjectName("pushButtonsubmit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_11.setText(_translate("Dialog", "Item:"))
        self.label_12.setText(_translate("Dialog", "Description:"))
        self.label_13.setText(_translate("Dialog", "Unit price:"))
        self.label_14.setText(_translate("Dialog", "Quantity:"))
        self.pushButtonsubmit.setText(_translate("Dialog", "SUBMIT"))
        self.lineEdititem.setPlaceholderText(_translate("Dialog", "enter item name"))
        self.lineEditdescription.setPlaceholderText(_translate("Dialog", "Enter item description"))
        self.lineEditunitprice.setPlaceholderText(_translate("Dialog", "Enter item unit price"))
        self.lineEditquantity.setPlaceholderText(_translate("Dialog", "Enter item quantity"))
        self.pushButtonsubmit_2.setText(_translate("Dialog", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
