# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(636, 546)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 631, 541))
        self.frame.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"background-color: rgb(255, 233, 249);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidgetitemadded = QtWidgets.QTableWidget(self.frame)
        self.tableWidgetitemadded.setGeometry(QtCore.QRect(0, 90, 501, 451))
        self.tableWidgetitemadded.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidgetitemadded.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidgetitemadded.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetitemadded.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetitemadded.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidgetitemadded.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetitemadded.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetitemadded.setObjectName("tableWidgetitemadded")
        self.tableWidgetitemadded.setColumnCount(5)
        self.tableWidgetitemadded.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetitemadded.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetitemadded.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetitemadded.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetitemadded.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetitemadded.setHorizontalHeaderItem(4, item)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(0, 50, 501, 31))
        self.lineEdit.setStyleSheet("font: 75 12pt \"Calibri\";\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 311, 41))
        self.label.setStyleSheet("color: rgb(170, 0, 127);\n"
"font: 75 italic 12pt \"MS Sans Serif\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButtontabrefresh = QtWidgets.QPushButton(self.frame)
        self.pushButtontabrefresh.setGeometry(QtCore.QRect(510, 100, 111, 31))
        self.pushButtontabrefresh.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border:none;\n"
"border-radius:10px;")
        self.pushButtontabrefresh.setObjectName("pushButtontabrefresh")
        self.pushButtonadditem = QtWidgets.QPushButton(self.frame)
        self.pushButtonadditem.setGeometry(QtCore.QRect(510, 160, 111, 31))
        self.pushButtonadditem.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border:none;\n"
"border-radius:10px;")
        self.pushButtonadditem.setObjectName("pushButtonadditem")
        self.pushButtondeleteitem = QtWidgets.QPushButton(self.frame)
        self.pushButtondeleteitem.setGeometry(QtCore.QRect(510, 220, 111, 31))
        self.pushButtondeleteitem.setStyleSheet("background-color: rgb(208, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border:none;\n"
"border-radius:10px;")
        self.pushButtondeleteitem.setObjectName("pushButtondeleteitem")
        self.labelprice = QtWidgets.QLabel(self.frame)
        self.labelprice.setGeometry(QtCore.QRect(310, 0, 71, 41))
        self.labelprice.setStyleSheet("color: rgb(170, 0, 127);\n"
"font: 75 italic 12pt \"MS Sans Serif\";")
        self.labelprice.setText("")
        self.labelprice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelprice.setObjectName("labelprice")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidgetitemadded.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "#"))
        item = self.tableWidgetitemadded.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Item"))
        item = self.tableWidgetitemadded.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Description"))
        item = self.tableWidgetitemadded.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "unit price"))
        item = self.tableWidgetitemadded.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "quantity"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Filter items"))
        self.label.setText(_translate("Dialog", "TOTAL INVENTORY AMOUNT IN KSH:"))
        self.pushButtontabrefresh.setText(_translate("Dialog", "Refresh"))
        self.pushButtonadditem.setText(_translate("Dialog", "+Add item"))
        self.pushButtondeleteitem.setText(_translate("Dialog", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
