# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'print.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(536, 611)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, -10, 541, 621))
        self.frame.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 70, 531, 501))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid green;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 531, 131))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label_2.setStyleSheet("border:none;\n"
"font: 75 12pt \"Roboto\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label_3.setStyleSheet("border:none;\n"
"font: 75 12pt \"Roboto\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 111, 21))
        self.label_4.setStyleSheet("border:none;\n"
"font: 75 12pt \"Roboto\";")
        self.label_4.setObjectName("label_4")
        self.labeldate = QtWidgets.QLabel(self.frame_3)
        self.labeldate.setGeometry(QtCore.QRect(400, 15, 101, 21))
        self.labeldate.setStyleSheet("border:none;\n"
"font: 75 11pt \"Roboto\";")
        self.labeldate.setText("")
        self.labeldate.setObjectName("labeldate")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 130, 531, 311))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setGeometry(QtCore.QRect(0, 110, 531, 111))
        self.tableWidget.setStyleSheet("border:1px solid black;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(230, 80, 61, 21))
        self.label_6.setStyleSheet("border:none;\n"
"font: 75 12pt \"Roboto\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(320, 220, 111, 31))
        self.label_7.setStyleSheet("background-color: rgb(185, 185, 185);\n"
"font: 75 12pt \"Roboto\";\n"
"border:1px solid black;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(320, 250, 111, 31))
        self.label_8.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(176, 176, 176);\n"
"font: 75 12pt \"Roboto\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(320, 280, 111, 31))
        self.label_9.setStyleSheet("border:1px solid black;\n"
"font: 75 12pt \"Roboto\";\n"
"background-color: rgb(177, 177, 177);")
        self.label_9.setObjectName("label_9")
        self.labelgrandtotal = QtWidgets.QLabel(self.frame_4)
        self.labelgrandtotal.setGeometry(QtCore.QRect(430, 220, 101, 31))
        self.labelgrandtotal.setStyleSheet("background-color: rgb(185, 185, 185);\n"
"font: 75 12pt \"Roboto\";\n"
"border:1px solid black;")
        self.labelgrandtotal.setText("")
        self.labelgrandtotal.setObjectName("labelgrandtotal")
        self.labelpayment = QtWidgets.QLabel(self.frame_4)
        self.labelpayment.setGeometry(QtCore.QRect(430, 250, 101, 31))
        self.labelpayment.setStyleSheet("background-color: rgb(185, 185, 185);\n"
"font: 75 12pt \"Roboto\";\n"
"border:1px solid black;")
        self.labelpayment.setText("")
        self.labelpayment.setObjectName("labelpayment")
        self.labelAmountdue = QtWidgets.QLabel(self.frame_4)
        self.labelAmountdue.setGeometry(QtCore.QRect(430, 280, 101, 31))
        self.labelAmountdue.setStyleSheet("background-color: rgb(185, 185, 185);\n"
"font: 75 12pt \"Roboto\";\n"
"border:1px solid black;")
        self.labelAmountdue.setText("")
        self.labelAmountdue.setObjectName("labelAmountdue")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label_14.setStyleSheet("border:none;\n"
"font: 75 12pt \"Roboto\";")
        self.label_14.setObjectName("label_14")
        self.labelcustomer = QtWidgets.QLabel(self.frame_4)
        self.labelcustomer.setGeometry(QtCore.QRect(100, 20, 151, 21))
        self.labelcustomer.setStyleSheet("border:none;\n"
"font: 75 12pt \"Roboto\";")
        self.labelcustomer.setText("")
        self.labelcustomer.setObjectName("labelcustomer")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 470, 221, 21))
        self.label_5.setStyleSheet("border:none;\n"
"font: 75 12pt \"Roboto\";")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(180, 580, 201, 31))
        self.pushButton.setStyleSheet("color: rgb(0, 85, 0);\n"
"font: 75 11pt \"Roboto\";\n"
"border:none;\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom: 2px solid green;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 580, 131, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Roboto\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 40, 131, 21))
        self.label.setStyleSheet("color: rgb(0, 85, 0);\n"
"font: 75 12pt \"Roboto\";")
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(10, 20, 511, 11))
        self.progressBar.setStyleSheet("background-color: rgb(117, 249, 255);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "My shop"))
        self.label_3.setText(_translate("Dialog", "193 ravine"))
        self.label_4.setText(_translate("Dialog", "+25475438908"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "#"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Item"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Unit price"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Amount"))
        self.label_6.setText(_translate("Dialog", "INVOICE"))
        self.label_7.setText(_translate("Dialog", "GRAND TOTAL"))
        self.label_8.setText(_translate("Dialog", "PAYMENT"))
        self.label_9.setText(_translate("Dialog", "Amount due"))
        self.label_14.setText(_translate("Dialog", "Customer:"))
        self.label_5.setText(_translate("Dialog", "Thank your for your business"))
        self.pushButton.setText(_translate("Dialog", "SELL WITHOUT PRINTING"))
        self.pushButton_2.setText(_translate("Dialog", "PRINT"))
        self.label.setText(_translate("Dialog", "Ready to print..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
